DATA:
    ROOT: ''
    TRAIN_FILE: ''
    VAL_FILE: ''
    DATASET: kinetics400
    NUM_FRAMES: 8
    NUM_CLASSES: 400
    LABEL_LIST: 'labels/kinetics_400_labels.csv'
MODEL:
    TYPE: 'videostorm_l'
    NAME: 'videostorm_l'
    NUM_CLASSES: 400
    DROP_PATH_RATE: 0.1
    PRETRAINED: null
    RESUME: null
TRAIN:
    PRETRAINED_PATH: ''
    BATCH_SIZE: 8
    ACCUMULATION_STEPS: 8